version: "3.9"

networks:
  problem-net:
    external: true

services:
  problem-db:
    image: "postgres:14.5-alpine"
    container_name: problem-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres      
    ports:
      - "5432:5432"
    networks:
      - problem-net
  
  problem-api:
    build: "./backend"
    container_name: problem-api
    environment:
      - DB_HOST=problem-db
      - DB_USER=postgres
      - DB_PASS=postgres      
      - DB_NAME=postgres
    ports:
      - "8000:8000"
    networks:
      - problem-net
    depends_on:
      - problem-db
    restart: on-failure
  
  problem-site:
    build: "./frontend"
    container_name: problem-site
    ports:
      - "3000:80"
    networks:
      - problem-net
    links:
      - problem-api

volumes:
  problem-data:
